### PR TITLE
fix: fe/infra boxes, resolves #1427

### LINKED ISSUE #1427: Infrastructure monitor design info boxes should match the design of the Uptime/Pagespeed monitor boxes
Here is how the currrent pagespeed monitor infoboxes look like: 

image

Here is how the infrastructure monitor infoboxes look like: 

image

We need to match the look of infra monitor boxes with the look of pagespeed/uptime monitor boxes. It would be good if the status box is green if the server is reachable, and red if it is not.

### PR DESCRIPTION
**Pull request by ajhollid**
This PR creates a reusable StatBox component that can be used throughout the app

- [x] Create `StatBox` component
- [x] Use consistently in Uptime Details, PageSpeed details, and Infrastructure details

### CODE REVIEW

File: Client/src/Components/StatBox/index.jsx [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+ *     sx={{ width: 300 }}
+ *   />
+ * )
+ *
+ * @returns {React.ReactElement} A styled box containing the statistic
+ */
+
+const StatBox = ({ heading, subHeading, sx }) => {
+	const theme = useTheme();
+	console.log(sx);
```
Comment (marcelluscaio) [inline Client/src/Components/StatBox/index.jsx:31]: A console slipped here

File: Client/src/Components/StatBox/index.jsx [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+				background: `linear-gradient(340deg, ${theme.palette.background.accent} 20%, ${theme.palette.background.main} 45%)`,
+				"& h2": {
+					fontSize: 13,
+					fontWeight: 500,
+					color: theme.palette.text.secondary,
+					textTransform: "uppercase",
+				},
+				"& p": {
+					fontSize: 18,
+					color: theme.palette.text.primary,
```
Comment (marcelluscaio) [inline Client/src/Components/StatBox/index.jsx:52]: Is our h2 smaller than our p?

**Review by marcelluscaio — COMMENTED** [review]
Good implementation, just had one question

File: Client/src/Components/StatBox/index.jsx (hunk 2 above)
Comment (ajhollid) [reply Client/src/Components/StatBox/index.jsx:52]: Honestly I'm not sure about the styling for this component, I just refactored as is so it's all in one place instead of duplicated 3 times. 

We can adjust styling as needed.

File: Client/src/Components/StatBox/index.jsx (hunk 1 above)
Comment (ajhollid) [reply Client/src/Components/StatBox/index.jsx:31]: Good catch again thanks

File: Client/src/Components/StatBox/index.jsx (hunk 2 above)
Comment (marcelluscaio) [reply Client/src/Components/StatBox/index.jsx:52]: Oh all right then! We can merge!
