### PR TITLE
Fix/translation fixes 2015

### LINKED ISSUE #2015: Translation fixes
- [x] Change "Sign up via email" to "Create super admin account"
- [x] Change to "By signing up, you..." "By creating an account, you agree to our Terms of Service and Privacy Policy" (this string should be in one, translatable sentence as a whole, like `By signing up, you agree to our <a href="...">Terms of Service</a> and <a href="...">Privacy Policy</a>.`

Image

- [x] Name and surname should be translatable

Image

- [x] Cover edge cases with names from various languages and scripts.

Here is a regex for this: `^[\p{L}\p{M}'’`\- ]+$`

- \p{L}: Matches any kind of letter from any language.
- \p{M}: Matches a combining mark (used for diacritics and accents).
- '’-`: Allows common punctuation characters used in names (apostrophes, typographic apostrophes, hyphens).
- : Allows spaces.
- +: Ensures that one or more characters are present.
- Anchors ^ and $: Ensure that the entire string follows the pattern.

Image

- [x] "Email" and "Email is required" should be translatable

Image

- [x] Instead of "Password", use "Enter your password"

Image

- [x] Change "Create a password" string to "Create your password"

### PR DESCRIPTION
**Pull request by mohicody**
## Describe your changes

1. Improved Name Validation:
Updated regex to support international names with proper error messages
Now accepts letters from any language, diacritics, apostrophes, and hyphens
2. Enhanced Translations:
Added email field and error message translations in all languages
Made validation error messages translatable 
3. UI Text Improvements:
Changed password field label to "Enter your password" for clarity
Fixed "super admin" capitalization 

These changes improve international name support and provide clearer guidance during registration while maintaining the application's design language.

## Write your issue number after "Fixes "

Fixes #2015 

## Please ensure all items are checked off before requesting a review. "Checked off" means you need to add an "x" character between brackets so they turn into checkmarks.

- [x] (Do not skip this or your PR will be closed) I deployed the application locally.
- [x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
- [x] I have included the issue # in the PR.
- [x] I have added i18n support to visible strings (instead of `<div>Add</div>`, use): 
```Javascript
const { t } = useTranslation();
<div>{t('add')}</div>
```
- [x] The issue I am working on is assigned to me.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [ ] I made sure font sizes, color choices etc are all referenced from the theme. I have no hardcoded dimensions.
- [x] My PR is granular and targeted to one specific feature.
- [ ] I took a screenshot or a video and attached to this PR if there is a UI change.

## Summary by CodeRabbit

- **New Features**
  - Improved localization support for registration forms, including new translation keys for first name, last name, email labels, and email validation messages in English, Russian, and Turkish.

- **Style**
  - Updated registration form labels and agreement text to use localized strings and enhanced formatting for "Terms of Service" and "Privacy Policy" links with embedded interactive elements.

- **Bug Fixes**
  - Enhanced validation for name fields to better support international characters and provide clearer error messages.

### CODE REVIEW

File: client/src/Pages/Auth/Register/Register.jsx [hunk 1]
```diff
@@ -67,42 +67,44 @@ const LandingPage = ({ isSuperAdmin, onSignup }) => {
...
-								window.open(
-									"https://bluewavelabs.ca/terms-of-service-open-source",
-									"_blank",
-									"noreferrer"
-								);
-							}}
-							sx={{
-								"&:hover": {
+						<Trans i18nKey="authRegisterBySigningUp">
+							By creating an account, you agree to our
```
Comment (ajhollid) [inline client/src/Pages/Auth/Register/Register.jsx:71]: What is going on here?  What is the purpose of the `Trans` component?

File: client/src/Pages/Auth/Register/Register.jsx [hunk 2]
```diff
@@ -67,42 +67,44 @@ const LandingPage = ({ isSuperAdmin, onSignup }) => {
...
-								);
-							}}
-							sx={{
-								"&:hover": {
+									},
+								}}
+							>
+								Terms of Service
+							</Typography>
+							and
```
Comment (ajhollid) [inline client/src/Pages/Auth/Register/Register.jsx:89]: Why have we removed the localistaion and replaced with hardcoded values?

**Review by ajhollid — COMMENTED** [review]
Can you explain this PR a bit more?  What is the purpose of the `Trans` component?  Why are we using that instead of the previous implementation?

**Review by ajhollid — APPROVED** [review]
Looks good, thanks for your contribution :rocket:
