### PR TITLE
Fix: Optionally show IP/URL of the monitor in status page

### LINKED ISSUE #2304: Optionally show IP/URL of the monitor in status page
If you are on a public Status page, only the name of the monitor should be displayed, the following specific web address or ping server address should be hidden.

This can be optional set under Settings. By default all IPs/URLs should be hidden.

### PR DESCRIPTION
**Pull request by AsimAhmedSiddiquii**
## Describe your changes

Added setting to toggle IP/URL from the public status page

## Write your issue number after "Fixes "

Fixes #2304 

## Please ensure all items are checked off before requesting a review. "Checked off" means you need to add an "x" character between brackets so they turn into checkmarks.

- [x] (Do not skip this or your PR will be closed) I deployed the application locally.
- [x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
- [x] I have included the issue # in the PR.
- [x] I have added i18n support to visible strings (instead of `<div>Add</div>`, use): 
```Javascript
const { t } = useTranslation();
<div>{t('add')}</div>
```
- [x] I have **not** included any files that are not related to my pull request, including package-lock and package-json if dependencies have not changed
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme. I have no hardcoded dimensions.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

When Disabled,
image
image

When Enabled,
image
image

## Summary by CodeRabbit

- **New Features**
  - Added a new setting to control the display of monitor IP addresses or URLs on the public status page.
  - Introduced a settings option allowing users to enable or disable the visibility of monitor URLs.
  - Updated the Settings page with a new section for configuring this display preference.
  - Updated monitor listings to conditionally show URLs based on the new setting.

- **Localization**
  - Added new translations for the URL display setting in English, Russian, and Turkish.

- **Validation**
  - Enhanced validation to require the new URL display setting in both client and server settings validation.

### CODE REVIEW

File: client/src/Pages/Settings/index.jsx [hunk 1]
```diff
@@ -67,6 +68,7 @@ const Settings = () => {
 		const { error } = settingsValidation.validate(newSettingsData.settings, {
 			abortEarly: false,
 		});
+		console.log(error)
```
Comment (Br0wnHammer) [inline client/src/Pages/Settings/index.jsx:71]: Kindly remove the console logs.

Comment (Br0wnHammer) [inline client/src/Pages/Settings/index.jsx:71]: Kindly remove the console log.

**Review by Br0wnHammer — APPROVED** [review]
A quite clean and efficient PR. Following all the right structure. 
LTGM!
Thanks for your contribution. 
Make sure to remove the console logs.

File: client/src/Features/UI/uiSlice.js [hunk 2]
```diff
@@ -20,6 +20,7 @@ const initialState = {
 		collapsed: false,
 	},
 	mode: initialMode,
+	statusURL: "disabled",
```
Comment (ajhollid) [inline client/src/Features/UI/uiSlice.js:23]: This value only has two states, and thus should be a `boolean` for clarity

Comment (AsimAhmedSiddiquii) [reply client/src/Features/UI/uiSlice.js:23]: ok sure will do that
