### PR TITLE
fix: update time format function, resolves #2477

### LINKED ISSUE #2477: Display last check time in readable format (e.g. 2 hours 30 minutes)
Convert Uptime Monitor > Monitor name > Last check from N.N hours to N hours X minutes, as seen here.

Check also days/weeks/months etc honor the same method (e.g 2 days 5 hours instead of 2.3 days). 

Image

### PR DESCRIPTION
**Pull request by ajhollid**
This PR updates the time formatting funciton to return a value with the two most significant units in human readable string format

E.g.

`"1d 20m"`
`"1h 20s"`
`"20s"`

- [x] Update time formatting function

image

## Summary by CodeRabbit

- **Refactor**
  - Improved duration formatting for time displays, now showing up to two abbreviated units (e.g., "2d 3h") for clearer readability.
  - Updated internal naming for loading state in uptime status boxes to better reflect its usage, with no impact on user-facing behavior.
  - Simplified duration display by consolidating time and units into a single formatted string for clearer and more consistent presentation.

### CODE REVIEW

File: client/src/Utils/timeUtils.js [hunk 1]
```diff
@@ -79,22 +79,35 @@ export const formatDurationSplit = (ms) => {
...
+	if (result.length < 2 && parts.minutes > 0) {
+		result.push(`${parts.minutes}m`);
+	}
+	if (result.length < 2 && parts.seconds > 0) {
+		result.push(`${parts.seconds}s`);
+	}
+
+	if (result.length === 0) {
+		// fallback for durations < 1s
+		return { time: 0, units: "seconds" };
```
Comment (Owaiseimdad) [inline client/src/Utils/timeUtils.js]: @ajhollid here the value of time is in numbers and other places it string. Is it fine or we can just do '0s'? I mean, just thinking of keeping it consistent.
