### PR TITLE
Fix/username flexibility added

### LINKED ISSUE #1561: Allow username to contain non-ascii letters or space + long names must fit in the user context menu
This check should be fixed so that name can contain space or diactric letters (e.g ç, ö, ğ).

Examples:

image

image

Also if a name is long, it must fit the user context menu by truncating: 

image

### PR DESCRIPTION
**Pull request by FlowerC9**
## Describe your changes

1.Support for Non-ASCII Characters – Updated the user name handling to allow spaces and non-ASCII characters, ensuring support for diverse names across different languages and character sets.

2.Truncation of Long Names – Implemented truncation for long names to prevent UI overflow, ensuring they fit within the available space while maintaining readability in both the main UI and the user context menu.

## Issue number

fixes #1561

## Please ensure all items are checked off before requesting a review. "Checked off" means you need to add an "x" character between brackets so they turn into checkmarks.

- [x] (Do not skip this or your PR will be closed) I deployed the application locally.
- [x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] The issue I am working on is assigned to me.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

before:
Screenshot 2025-02-26 115631

after:
Screenshot 2025-02-26 210924

### CODE REVIEW

File: src/Components/Sidebar/index.jsx [hunk 1]
```diff
@@ -628,10 +628,19 @@ function Sidebar() {
 				) : (
 					<>
 						<Avatar small={true} />
-						<Box ml={theme.spacing(2)}>
+						<Box
+							ml={theme.spacing(2)}
+							sx={{ maxWidth: "150px", overflow: "hidden" }}
```
Comment (ajhollid) [inline src/Components/Sidebar/index.jsx:633]: Can we use a relative value here for width?

**Review by ajhollid — CHANGES_REQUESTED** [review]
Looks good for the most part, can we use a relative value for the maxWidth here so it displays well on various sized screens?

File: src/Components/Sidebar/index.jsx (hunk 1 above)
Comment (FlowerC9) [reply src/Components/Sidebar/index.jsx]: i have applied relative width to sidebar profile view could you @ajhollid  please check if it's ok?

Comment (FlowerC9) [reply src/Components/Sidebar/index.jsx]: also @ajhollid would you like me to raise a pr for the backend validation part so that it can sync.

Comment (ajhollid) [reply src/Components/Sidebar/index.jsx]: @FlowerC9 yes please do, let's get the back end in sync before we merge this or we will have problems if the user submits unacceptable names to the backend.

**Review by ajhollid — APPROVED** [review]
