### PR TITLE
FIX-1848 UI design changes

### LINKED ISSUE #1848: Small UI fixes
- [x] Divider is not vertically aligned
- [x]  The search component is a bit "higher" than our usual 34px text input widget.

Image

- [ ] Bg color of this area to #1c1c1c and border to #515151 or nearest color

Image

- [ ] For Teams and Profile we don't really need that bounding box as it's not present in other pages.

Image

- [ ] Maintenance window time selector up/down boxes need a darker color from the palette

Image

- [ ] The maintenance window time selector popup needs color fixes

Image

- [ ] We don't really use line edit explanation areas here, so better remove.

Image

- [ ] Highlight colors should be fixed (should be #324153 just like the other dropdown highlight colors). This should be fixed component-wise, not just in this screen

Image

- [ ] Maintenance duration window notification shouldn't wrap

Image

- [ ] A pagination should be there only if there is a need for it.

Image

- [ ] While creating an infrastructure monitor, the links are invisible both for dark and light themes.

Image

### PR DESCRIPTION
**Pull request by Owaiseimdad**
## Describe your changes
1. Removed the common code and added a new component in order to reuse it in future.
2. Also removed the _sx={{ margin: theme.spacing(6) }}_ which was the causing the issues in the UI.

Briefly describe the changes you made and their purpose.
-> The alignment of divider line for the left and right box in the contents tab in status page.
-> Made changes in order to avoid any repeated code in the main code file. Ideally, even each section should be in different file but that will be abundance of files and we don’t need to increase it now. But atleast the developer should not worry about title and description component.

## Issue number
Small UI fixes #1848

## Please ensure all items are checked off before requesting a review. "Checked off" means you need to add an "x" character between brackets so they turn into checkmarks.

- [x] (Do not skip this or your PR will be closed) I deployed the application locally.
- [x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
- [x] I have included the issue # in the PR.
- [x] I have labelled the PR correctly.
- [x] The issue I am working on is assigned to me.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.
Screenshot 2025-03-01 at 10 27 55 PM

### CODE REVIEW

File: src/Utils/Theme/constants.js [hunk 1]
```diff
@@ -290,6 +291,16 @@ const newSemanticColors = {
...
+	alert: {
+		background: {
+			light: newColors.gray200,
+			dark: newColors.gray900,
+		},
+		border: {
+			light: newColors.blueGray600,
+			dark: newColors.blueGray900,
+		},
+	},
```
Comment (ajhollid) [inline src/Utils/Theme/constants.js:303]: These values will not work with MUI components which is the purpose of the theme.

Please see [theme docs](https://mui.com/material-ui/customization/palette/?srsltid=AfmBOorIhzVlr07sQdwGvVVmRTAphzTuqjj2UuQsSdpQwX4W8hWqKsOu) and be familiar with how the theme works before modifying the theme.

File: src/Pages/StatusPage/Create/Components/Tabs/SectionStack.jsx [hunk 2]
```diff
@@ -0,0 +1,26 @@
+import { Stack, Typography } from "@mui/material";
+import ConfigBox from "../../../../../Components/ConfigBox";
+import PropTypes from "prop-types";
+import { useTheme } from "@emotion/react";
+
+// This can be used to add any extra/additional section/stacks on top of existing sections on the tab
+const SectionStack = ({ title, description, children }) => {
```
Comment (ajhollid) [inline src/Pages/StatusPage/Create/Components/Tabs/SectionStack.jsx:7]: This is a worthy refactor.  This comonent is used throughout many pages in fact, all the "Create" and "Settings" pages I believe.

A more semanitc name might be useful here, perahps "ConfigStacK" since it is generally used for config?

**Review by ajhollid — CHANGES_REQUESTED** [review]
The component refactor looks good, but the theme usage isn't correct.  Please see the docs to see how to define MUI compatible palette items

File: src/Utils/Theme/constants.js (hunk 1 above)
Comment (Owaiseimdad) [reply src/Utils/Theme/constants.js:303]: @ajhollid , yep thanks for providing reference here.

**Review by ajhollid — APPROVED** [review]
