### PR TITLE
Fix: Infra Monitors Filters

### LINKED ISSUE #2233: When a search filter is applied and there are no corresponding lines in the table, the placeholder is shown
How to replicate: 

1. Click "up" when there are no "up" monitors

Image

2. Placeholder is shown:

Image

### PR DESCRIPTION
**Pull request by Br0wnHammer**
## Describe your changes

This PR addresses a bug on the infrastructure monitors page. Previously, selecting a filter that was the opposite of the available monitors would lead to a placeholder screen being displayed.

Fixes #2233 

## Please ensure all items are checked off before requesting a review. "Checked off" means you need to add an "x" character between brackets so they turn into checkmarks.

- [x] (Do not skip this or your PR will be closed) I deployed the application locally.
- [x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
- [x] I have included the issue # in the PR.
- [x] I have added i18n support to visible strings (instead of `<div>Add</div>`, use): 
```Javascript
const { t } = useTranslation();
<div>{t('add')}</div>
```
- [x] I have **not** included any files that are not related to my pull request, including package-lock and package-json if dependencies have not changed
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme. I have no hardcoded dimensions.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

Screenshot 2025-05-12 144257
Screenshot 2025-05-12 144403
Screenshot 2025-05-12 144534

## Summary by CodeRabbit

- **New Features**
  - Added a message "No monitors found" to be displayed when the monitors table is empty.

- **Refactor**
  - Improved the logic for displaying fallback content when no monitors are available.

### CODE REVIEW

File: client/src/Pages/Infrastructure/Monitors/Components/MonitorsTable/index.jsx [hunk 1]
```diff
@@ -68,8 +68,16 @@ const MonitorsTable = ({ shouldRender, monitors, isAdmin, handleActionMenuDelete
 			),
 		},
 		{ id: "cpu", content: t("cpu"), render: (row) => <CustomGauge progress={row.cpu} /> },
-		{ id: "memory", content: t("memory"), render: (row) => <CustomGauge progress={row.mem} /> },
-		{ id: "disk", content: t("disk"), render: (row) => <CustomGauge progress={row.disk} /> },
+		{
```
Comment (Br0wnHammer) [inline client/src/Pages/Infrastructure/Monitors/Components/MonitorsTable/index.jsx:71]: Some formatting was needed in this section.

**Review by ajhollid — APPROVED** [review]
