### PR TITLE
fix(ui): shorten URL label and resize notification button (#2470)

### LINKED ISSUE #2470: Floating strings
Image

- The tooltip showing "Checking every 3 minutes" appears to be floating - need shorter URL there
- Send test notifications button need to enlarge based on the string

### PR DESCRIPTION
**Pull request by deepanshu2711**
Closes #2470

🐞 What’s Fixed
Truncate long monitor URLs in the tooltip (“Checking every …”) to prevent text overflow and floating UI.

Enlarge the Send test notifications button to ensure the full label is visible without wrapping or cropping.

✅ How to Test
Hover over a monitor entry with a long URL and verify the tooltip displays a shortened, well-truncated URL.

Confirm the Send test notifications button renders at an appropriate width and does not clip the text.

- [x] (Do not skip this or your PR will be closed) I deployed the application locally.
- [x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
- [x] I have included the issue # in the PR.
- [x] I have added i18n support to visible strings (instead of `<div>Add</div>`, use): 
```Javascript
const { t } = useTranslation();
<div>{t('add')}</div>
```
- [x] I have **not** included any files that are not related to my pull request, including package-lock and package-json if dependencies have not changed
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme. I don't have any hardcoded dimensions.
- [x] My PR is granular and targeted to one specific feature.
- [x] I ran `npm run format` in server and client directories, which automatically formats your code.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

checkmate

## Summary by CodeRabbit

- **Style**
  - Improved button appearance by preventing text wrapping on the "Send Test Notifications" button.
  - Enhanced monitor URL display by consistently formatting and truncating long URLs for a cleaner look.

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
UI wise looks good to me!

**Review by ajhollid — CHANGES_REQUESTED** [review]
This PR is not formatted with our project standard `.prettierrc` so we can't easily tell what code you've changed as the whole file is marked as changed.

Please run `npm run format` in your `client` dir and format before submission.

Thank you!

**Comment by deepanshu2711** [comment]
@ajhollid Done please check

File: client/src/Components/MonitorDetailsControlHeader/status.jsx [hunk 1]
```diff
@@ -33,8 +34,15 @@ const Status = ({ monitor }) => {
...
 				<PulseDot color={statusColor[determineState(monitor)]} />
-				<Typography variant="monitorUrl">
-					{monitor?.url?.replace(/^https?:\/\//, "") || "..."}
+				<Typography
+					variant="monitorUrl"
+					noWrap
+				>
+					{monitor?.url
+						? monitor.url?.length > URL_TRUNCATION_LENGTH
+							? `${monitor.url.replace(/^https?:\/\//, "")?.slice(0, URL_TRUNCATION_LENGTH)}…`
```
Comment (Br0wnHammer) [inline client/src/Components/MonitorDetailsControlHeader/status.jsx]: It would be more efficient to manage the URL logic beforehand, allowing the component to remain free from handling such logic.

**Review by Br0wnHammer — CHANGES_REQUESTED** [review]
Looks good for most aspects. I recommend moving this to the `globalTheme.js` file so that it can be applied uniformly across all instances with a `monitorUrl` variant.

**Comment by deepanshu2711** [comment]
@Br0wnHammer check now please

File: client/src/Components/MonitorDetailsControlHeader/status.jsx [hunk 2]
```diff
@@ -23,6 +24,7 @@ import { useMonitorUtils } from "../../Hooks/useMonitorUtils";
 const Status = ({ monitor }) => {
 	const theme = useTheme();
 	const { statusColor, determineState } = useMonitorUtils();
+	const URL_TRUNCATION_LENGTH = 55;
```
Comment (ajhollid) [inline client/src/Components/MonitorDetailsControlHeader/status.jsx]: This is a constant, you can move this out of the component, no need to recreate on every render

**Review by ajhollid — CHANGES_REQUESTED** [review]
In general it looks good, we can move the contant value out of the component however, there's no need to recreate that var on every render

File: client/src/Components/MonitorDetailsControlHeader/status.jsx (hunk 2 above)
Comment (deepanshu2711) [reply client/src/Components/MonitorDetailsControlHeader/status.jsx]: @ajhollid Done

**Review by ajhollid — APPROVED** [review]
Looks good, thanks for revisions here!
