### PR TITLE
fix: Password validation on account

### LINKED ISSUE #1274: Password validation on Account > Password
If you type in your password, then add a new password that is incomplete e.g. Ad,tree! (without a number), and set the confirm password to Ad,tree! , and then add  a number e.g. 1 to your password, without changing the confirm password, all validations will pass, even though password and confirm password are different

### PR DESCRIPTION
**Pull request by peterpardo**
### Summary
This PR fixes the issue for the password validation under `Account > Password`

### Changes Made
- Updated password validation logic
- Added `getTouchedFieldErrors()` util function for errors

### Related Issue/s
Fixes #1274 

### Screenshots / Demo Video

https://github.com/user-attachments/assets/d4d7334a-d439-4a50-b19e-1c4c4e8d98cd

### Additional Context
N/A

### CODE REVIEW

**Review by marcelluscaio — APPROVED** [review]
Really nice implementation, @peterpardo !

File: Client/src/Validation/error.js [hunk 1]
```diff
@@ -8,6 +8,31 @@ const buildErrors = (prev, id, error) => {
...
+/**
+ * Processes Joi validation errors and returns a filtered object of error messages for fields that have been touched.
+ *
+ * @param {Object} validation - The Joi validation result object.
+ * @param {Object} validation.error - The error property of the validation result containing details of validation failures.
+ * @param {Object[]} validation.error.details - An array of error details from the Joi validation. Each item contains information about the path and the message.
+ * @param {Object} touchedErrors - An object representing which fields have been interacted with. Keys are field IDs (field names), and values are booleans indicating whether the field has been touched.
+ * @returns {Object} - An object where keys are the field IDs (if they exist in `touchedErrors` and are in the error details) and values are their corresponding error messages.
+ */
+const getTouchedFieldErrors = (validation, touchedErrors) => {
```
Comment (ajhollid) [inline Client/src/Validation/error.js:20]: Nicely done, really appreciate the JSdocs

**Review by ajhollid — APPROVED** [review]
Great work @peterpardo, thank you again for your contribution!
