### PR TITLE
fix: cpu frequency parsing, resolves #1620

### LINKED ISSUE #1620: CPU Frequency Not Displayed on Main Infrastructure Dashboard
Description:

Issue: CPU Frequency is not being displayed on the main infrastructure dashboard, despite being available under the monitor details for individual devices.
Expected Behavior: CPU Frequency should be visible as a metric on the main infrastructure dashboard alongside other relevant system information (e.g., CPU Usage, Memory Usage).
Actual Behavior: CPU Frequency is missing from the main dashboard view.
Possible Causes:
Typo in variable name: The variable used to store/retrieve CPU Frequency data might contain a typo, preventing it from being correctly displayed on the main dashboard.
Incorrect variable name: The variable name used in the dashboard template might not match the actual variable name used to store the CPU Frequency data.
Steps to Reproduce:
Navigate to the main infrastructure dashboard in Checkmate.
Observe that CPU Frequency is not listed among the available metrics.
Select a specific device from the device list.
Navigate to the monitor details for the selected device.
Verify that CPU Frequency is displayed as a metric within the device's monitor details.

Environment: 2.0.1 and 2.0.2
Operating system Unraid v7.0.2
Browser and version Edge v132 and Chrome v130

Screenshots provided in the discord channel

### PR DESCRIPTION
**Pull request by ajhollid**
This PR fixes an error which prevented CPU frequency from being properly parsed.

- [x] Fix CPU frequency parsing

image

### CODE REVIEW

File: Client/src/Pages/Infrastructure/index.jsx [hunk 1]
```diff
@@ -149,8 +149,9 @@ function Infrastructure() {
 	];
 
 	const monitorsAsRows = monitors.map((monitor) => {
+		console.log(monitor);
```
Comment (mertssmnoglu) [inline Client/src/Pages/Infrastructure/index.jsx:152]:
```suggestion
```

File: Client/src/Pages/Infrastructure/index.jsx [hunk 2]
```diff
@@ -181,6 +182,7 @@ function Infrastructure() {
 	});
 
 	let isActuallyLoading = isLoading && monitors?.length === 0;
+	console.log(monitorsAsRows);
```
Comment (mertssmnoglu) [inline Client/src/Pages/Infrastructure/index.jsx:185]:
```suggestion
```

**Review by mertssmnoglu — APPROVED** [review]
Thanks for the fix! @ajhollid 
LGTM

**Comment by ajhollid** [comment]
> LGTM

Thanks for the review!
