### PR TITLE
fix(status-page): toggles for charts and uptime % 

### LINKED ISSUE #2864: Features tick boxes on status page config dont work
**Describe the bug**

**To Reproduce**
1. Go to configure status page
2. Click on 'Contents'
3. Tick any of the 'Features' tick boxes
4. Check status page nto no change

**Expected behavior**
Each boxes should make the intended change on status page

**Screenshots**
N/A - pretty self explanitory

**Desktop (please complete the following information):**
N/A - happens across all browsers i tested

**Additional context**

### PR DESCRIPTION
**Pull request by antonstrover**
## Describe your changes
- Resolve React warnings on Status page: wrap `Bar` with `forwardRef`, ensure `Tooltip` child supports refs, and compute `width` as a string via `useMediaQuery` to remove prop-type errors.
- Improve chart UX: enforce a small minimum bar height so tiny values remain visible.
- Add status page controls: gate uptime percentage and charts via `statusPage.showUptimePercentage` and `statusPage.showCharts`, and adjust layout when charts are hidden; pass `statusPage` prop through.
- Add resilience: handle missing `uptimePercentage` in `useMonitorUtils` by showing “--” with secondary color.
- Backend updates: compute `monitors.uptimePercentage` in Mongo aggregation; replace wildcard CORS `allowedHeaders` with an explicit list.

## Write your issue number after "Fixes "

Fixes #2864 

## Please ensure all items are checked off before requesting a review. "Checked off" means you need to add an "x" character between brackets so they turn into checkmarks.
- [x] (Do not skip this or your PR will be closed) I deployed the application locally.
- [x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
- [x] I have included the issue # in the PR.
- [x] I have added i18n support to visible strings (or did not introduce new visible strings).
- [x] I have **not** included any files that are not related to my pull request, including package-lock and package-json if dependencies have not changed.
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme.
- [x] My PR is granular and targeted to one specific feature.
- [x] I ran `npm run format` in server and client directories, which automatically formats your code.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change. 

## Summary by CodeRabbit

* **New Features**
  * Status page can show or hide per-monitor charts based on page settings.
  * When charts are hidden, monitor list layout expands for improved readability.
  * Uptime percentage for each monitor is now displayed for clearer at-a-glance reliability insights.
  * Chart and label areas dynamically adjust to maintain a balanced layout whether charts are shown or hidden.

### CODE REVIEW

**Comment by ajhollid** [comment]
Hi @antonstrover, 

Can you please separate this pull request into individual features/fixes so we can address them one at a time?

I realize the changes aren't huge, but it is far easier for us to review and approve code if each PR is focused on one feature or fix.

Thank you!

File: client/src/Components/Charts/StatusPageBarChart/index.jsx
Comment (antonstrover) [inline client/src/Components/Charts/StatusPageBarChart/index.jsx:1]: Imports

Added forwardRef from react.

Kept useTheme, MUI imports, and utilities.

Component: Bar

Before: 

`const Bar = ({ width, height, backgroundColor, borderRadius, children, ...otherProps }) => { … }`

After is wrapped with forwardRef: 

`const Bar = forwardRef((props, ref) => …)  `so MUI Tooltip can attach a ref to the rendered element.

Forwarded ref to `<Box ref={ref} … />`

Continued to compute `sx={{ borderRadius: borderRadius || theme.spacing(1.5) }}` using theme.spacing(1.5) gives you a consistent fallback radius.

File: client/src/Pages/StatusPage/Status/Components/MonitorsList/index.jsx
Comment (antonstrover) [inline client/src/Pages/StatusPage/Status/Components/MonitorsList/index.jsx:1]: Signature & props

Before: const MonitorsList = ({ isLoading = false, shouldRender = true, monitors = [] }) => { … }

After: const MonitorsList = ({ isLoading = false, shouldRender = true, monitors = [], statusPage = {} }) => { … }
Added statusPage input so the list can respect page-level toggles.

Rendering changes

Previously always rendered the chart area; you had:

```
<Box flex={9}>
  <StatusPageBarChart checks={(monitor?.checks).slice().reverse()} />
</Box>
```
Now guard it:
```
{statusPage.showCharts !== false && (
  <Box flex={9}>
    <StatusPageBarChart checks={monitor?.checks?.slice()?.reverse()} />
  </Box>
)}

```

Meaning: charts render by default, but a `showCharts: false` flag on the status page hides them.

PropTypes

Added statusPage: PropTypes.object alongside the existing monitors: PropTypes.array.isRequired.

File: server/src/db/mongo/modules/statusPageModule.js
Comment (antonstrover) [inline server/src/db/mongo/modules/statusPageModule.js:1]: Added a $lookup to join monitorstats:

`{
  $lookup: {
    from: "monitorstats",
    localField: "monitors._id",
    foreignField: "monitorId",
    as: "monitors.stats",
  }
}
`
Use precomputed uptime rather than recalculating:
`
{ $addFields: {
    "monitors.uptimePercentage": { $arrayElemAt: ["$monitors.stats.uptimePercentage", 0] },
}}
`

File: client/src/Components/Charts/StatusPageBarChart/index.jsx [hunk 1]
```diff
@@ -17,23 +17,27 @@ import PropTypes from "prop-types";
  * @returns {JSX.Element} The Bar component.
  */
 
-const Bar = ({ width, height, backgroundColor, borderRadius, children }) => {
-	const theme = useTheme();
+const Bar = forwardRef(
```
Comment (ajhollid) [inline client/src/Components/Charts/StatusPageBarChart/index.jsx:20]: Components wrapped in `forwardRef` should have a display name, you can set something like

`Bar.displayName = "Bar";`

**Review by ajhollid — CHANGES_REQUESTED** [review]
Everything looks good here to me! 

Could you just set the display name for the newly wrapped `Bar` component?  Other than that, I think we're all good.

Thanks for the contribution!

**Comment by antonstrover** [comment]
added display name

**Comment by antonstrover** [comment]
I am unfamiliar with conflicts and resolving them so that was a little alien to me, but i think i fixed it lol

**Comment by gorkem-bwl** [comment]
> I am unfamiliar with conflicts and resolving them so that was a little alien to me, but i think i fixed it lol

Suggest using claude code or codex for this purpose, and carefully examine what it does to resolve the conflicts, then note it down and use in the future :)

**Comment by antonstrover** [comment]
> > I am unfamiliar with conflicts and resolving them so that was a little alien to me, but i think i fixed it lol
> 
> Suggest using claude code or codex for this purpose, and carefully examine what it does to resolve the conflicts, then note it down and use in the future :)

Its not the actual resolution, that is fine - Its the UI's and stuff. Just need a few youtube videos when i get a minute haha

thank you for the advice though :)
