### PR TITLE
# Fix: Save button disabled when timezone changes (#2343)

### LINKED ISSUE #2343: Save button is disabled when timezone changes
Image

### PR DESCRIPTION
**Pull request by mohicody**
## Problem
When changing the timezone in the Settings page, the Save button remains disabled, preventing users from saving their timezone preference. After refreshing the page, the Save button works correctly.

## Root Cause
1. The `timezone` field was missing from both frontend and backend validation schemas
2. When changing the timezone, the local component state wasn't properly updated
3. The backend API validation rejected the timezone field since it wasn't in the allowed fields list

## Solution
1. Added `timezone` field to the frontend validation schema in `validation.js`
2. Added `timezone` field to the backend validation schema in `server/validation/joi.js`
3. Fixed state synchronization in the Settings component to properly update when timezone changes

## Write your issue number after "Fixes "

Fixes #2343 

## Please ensure all items are checked off before requesting a review. "Checked off" means you need to add an "x" character between brackets so they turn into checkmarks.

- [x] (Do not skip this or your PR will be closed) I deployed the application locally.
- [x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
- [x] I have included the issue # in the PR.
- [x] I have added i18n support to visible strings (instead of `<div>Add</div>`, use): 
```Javascript
const { t } = useTranslation();
<div>{t('add')}</div>
```
- [x] I have **not** included any files that are not related to my pull request, including package-lock and package-json if dependencies have not changed
- [x] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [x] I made sure font sizes, color choices etc are all referenced from the theme. I have no hardcoded dimensions.
- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

https://github.com/user-attachments/assets/626cc41c-f290-4a6a-9a54-d9cf8f375a84

## Summary by CodeRabbit

- **New Features**
  - Added support for updating and validating the timezone setting in user settings.

- **Bug Fixes**
  - Ensured the displayed timezone value in settings stays in sync with user changes.

### CODE REVIEW

File: client/src/Pages/Settings/index.jsx [hunk 1]
```diff
@@ -85,6 +85,8 @@ const Settings = () => {
 
 		if (name === "timezone") {
 			dispatch(setTimezone({ timezone: value }));
+			// Make sure to update settingsData with the new timezone value
+			setSettingsData(newSettingsData);
```
Comment (ajhollid) [inline client/src/Pages/Settings/index.jsx:89]: This shouldn't be necessary, it's called at the end of the handler :thinking: Any reason to call it here as well?

**Review by ajhollid — CHANGES_REQUESTED** [review]
Any reason to call `setSettignsData` in the timezone block?

**Review by ajhollid — APPROVED** [review]
