### PR TITLE
Issue-2238: Fixes the error messages on various forms.

### LINKED ISSUE #2238: Translation message issues on various forms
#### 1. Reset password form
***Steps to reproduce the behavior***
1. Go to `/forgot-password` page
2. Enter an invalid email address
3. You should see error message `authRegisterEmailInvalid`

***Expected behavior***
Correct error message should be `Please enter a valid email address`.

#### 2. Signup form step 1
***Steps to reproduce the behavior***
1. Go to `/register` page
2. Keep Surname field empty
3. You should see error message as `Surname is required`

***Expected behavior***
Correct error message should be `Please enter a valid email address`.

#### 3. Signup form step 2
***Steps to reproduce the behavior***
1. Go to `/register` page
2. Fill-up the  Name and Surname field and go to next step
3. Enter an invalid email address
4. You should see error message `authRegisterEmailInvalid`

***Expected behavior***
Correct error message should be `Please enter a valid email address`.

**Screenshots**
| Form Name | Current behavior  | Expected behavior |
| ------------- | ------------- | ------------- |
| Reset Password  |  Image| Image |
| Signup form step 1  |Image| Image|
| Signup form step 2  |Image| Image|

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [135.0.7049.115 ]

### PR DESCRIPTION
**Pull request by sonvir249**
## Describe your changes

Fixes the error message on signup and reset form.

## Write your issue number after "Fixes "

Fixes #2238

- [x] My PR is granular and targeted to one specific feature.
- [x] I took a screenshot or a video and attached to this PR if there is a UI change.

**Screenshots**
| Form Name | Current behavior  | Expected behavior |
| ------------- | ------------- | ------------- |
| Reset Password  |  Image| Image |
| Signup form step 1  |Image| Image|
| Signup form step 2  |Image| Image|

## Summary by CodeRabbit

- **New Features**
  - Error messages for email fields in Forgot Password and Register forms are now localized.
  - Surname validation now provides specific error messages distinct from first name validation.

- **Refactor**
  - Improved consistency in form validation schemas for better maintainability and readability.

### CODE REVIEW

File: client/src/Pages/Auth/ForgotPassword.jsx [hunk 1]
```diff
@@ -185,7 +185,7 @@ const ForgotPassword = () => {
 							value={form.email}
 							onChange={handleChange}
 							error={errors.email ? true : false}
-							helperText={errors.email}
+							helperText={t(errors.email)}
```
Comment (Br0wnHammer) [inline client/src/Pages/Auth/ForgotPassword.jsx:188]: Any particular reason for this change? Also, can you share a UI SS.

File: client/src/Pages/Auth/Register/StepTwo/index.jsx [hunk 2]
```diff
@@ -68,11 +68,14 @@ function StepTwo({ form, errors, onSubmit, onChange, onBack }) {
...
-						errors.email.includes("valid email") ? t("authRegisterEmailInvalid") :
-						errors.email
-					)}
+						helperText={
+							errors.email &&
+							(errors.email.includes("required")
+								? t("authRegisterEmailRequired")
+								: errors.email.includes("valid email")
+									? t("authRegisterEmailInvalid")
+									: t(errors.email))
```
Comment (Br0wnHammer) [inline client/src/Pages/Auth/Register/StepTwo/index.jsx:77]: Same thing here.

File: client/src/Validation/validation.js [hunk 3]
```diff
@@ -53,7 +66,7 @@ const passwordSchema = joi
 
 const credentials = joi.object({
 	firstName: nameSchema,
-	lastName: nameSchema,
+	lastName: surnameSchema,
```
Comment (Br0wnHammer) [inline client/src/Validation/validation.js:69]: A better name would be `lastnameSchema`.

File: client/src/Validation/validation.js [hunk 4]
```diff
@@ -152,20 +165,21 @@ const monitorValidation = joi.object({
...
-		is: "port",
-		then: joi.required().messages({
-			"number.base": "Port must be a number.",
-			"number.min": "Port must be at least 1.",
-			"number.max": "Port must be at most 65535.",
-			"any.required": "Port is required for port monitors.",
+	port: joi
+		.number()
+		.integer()
+		.min(1)
```
Comment (Br0wnHammer) [inline client/src/Validation/validation.js:171]: What is the change here?

File: client/src/Validation/validation.js [hunk 5]
```diff
@@ -252,15 +266,16 @@ const statusPageValidation = joi.object({
...
+const settingsValidation = joi
+	.object({
+		ttl: joi.number().required().messages({
+			"string.empty": "Please enter a value",
+			"number.base": "Please enter a valid number",
+			"any.required": "Please enter a value",
+		}),
+		pagespeedApiKey: joi.string().allow("").optional(),
+	})
+	.unknown(true);
```
Comment (Br0wnHammer) [inline client/src/Validation/validation.js:278]: Again, please refrain from using formatting on the code that is not supported by us. Makes the diff larger than it is.

File: client/src/Validation/validation.js [hunk 6]
```diff
@@ -377,5 +395,5 @@ export {
 	advancedSettingsValidation,
 	infrastructureMonitorValidation,
 	statusPageValidation,
-	logoImageValidation
+	logoImageValidation,
```
Comment (Br0wnHammer) [inline client/src/Validation/validation.js:398]: Same.

**Review by Br0wnHammer — CHANGES_REQUESTED** [review]
Overall a UI SS is needed to review completely. Apart from that formatted code needs to omitted out of the PR. Larger diffs than required.

File: client/src/Validation/validation.js [hunk 7]
```diff
@@ -11,7 +11,20 @@ const nameSchema = joi
 	.messages({
 		"string.empty": "Name is required",
 		"string.max": "Name must be less than 50 characters",
-		"string.pattern.base": "Name must contain only letters, spaces, apostrophes, or hyphens"
+		"string.pattern.base":
+			"Name must contain only letters, spaces, apostrophes, or hyphens",
+	});
+
+const surnameSchema = joi
```
Comment (Owaiseimdad) [inline client/src/Validation/validation.js:18]: @sonvir249 , it looks like the same Joi schema is being repeated. Let's simplify this by renaming it to nameStringSchema. Also, instead of using name and surname, let's generalize it to something like characters or simply indicate that input is required. Please make sure to apply the DRY (Don't Repeat Yourself) principle wherever applicable.

File: client/src/Pages/Auth/Register/StepTwo/index.jsx (hunk 2 above)
Comment (Owaiseimdad) [inline client/src/Pages/Auth/Register/StepTwo/index.jsx:77]: @sonvir249 does anything like t(errors.email) exists in local file and, is it even intented to be from translation or is it just errors.email?

File: client/src/Pages/Auth/ForgotPassword.jsx (hunk 1 above)
Comment (Owaiseimdad) [inline client/src/Pages/Auth/ForgotPassword.jsx:188]: same here, I don't see anything like errors.email in translation file, let me know if I am missing anything here.
@sonvir249

**Review by Owaiseimdad — CHANGES_REQUESTED** [review]
@sonvir249 please make your changes and test it locally and add screenshots for reference.

File: client/src/Validation/validation.js [hunk 8]
```diff
@@ -252,15 +266,16 @@ const statusPageValidation = joi.object({
...
-const settingsValidation = joi.object({
-	ttl: joi.number().required().messages({
-		"string.empty": "Please enter a value",
-		"number.base": "Please enter a valid number",
-		"any.required": "Please enter a value"
-	}),
-	pagespeedApiKey: joi.string().allow("").optional(),
-})
-.unknown(true);
+const settingsValidation = joi
```
[the remark this answers is not in the document]
Comment (sonvir249) [reply client/src/Validation/validation.js]: @Owaiseimdad Removed this formatting change.

File: client/src/Pages/Auth/ForgotPassword.jsx (hunk 1 above)
Comment (sonvir249) [reply client/src/Pages/Auth/ForgotPassword.jsx:188]: @Br0wnHammer I added the detailed screenshots in the issue #2238. I've attached the SS in PR too.

File: client/src/Pages/Auth/Register/StepTwo/index.jsx (hunk 2 above)
Comment (sonvir249) [reply client/src/Pages/Auth/Register/StepTwo/index.jsx]: @Br0wnHammer removed unnecessary changes.

File: client/src/Validation/validation.js (hunk 3 above)
Comment (sonvir249) [reply client/src/Validation/validation.js]: @Br0wnHammer done.

File: client/src/Validation/validation.js (hunk 4 above)
Comment (sonvir249) [reply client/src/Validation/validation.js]: @sonvir249 removed unnecessary change

File: client/src/Validation/validation.js (hunk 5 above)
Comment (sonvir249) [reply client/src/Validation/validation.js]: @Br0wnHammer removed unnecessary change

File: client/src/Validation/validation.js (hunk 6 above)
Comment (sonvir249) [reply client/src/Validation/validation.js]: @Br0wnHammer removed unnecessary change

File: client/src/Validation/validation.js (hunk 7 above)
Comment (sonvir249) [reply client/src/Validation/validation.js]: @Br0wnHammer removed unnecessary change

File: client/src/Pages/Auth/Register/StepTwo/index.jsx (hunk 2 above)
Comment (sonvir249) [reply client/src/Pages/Auth/Register/StepTwo/index.jsx]: @Owaiseimdad `errors.email` returns the `authRegisterEmailInvalid` and `authRegisterEmailRequired` and it should be passed in `t()` to print the translation string.

File: client/src/Pages/Auth/ForgotPassword.jsx (hunk 1 above)
Comment (sonvir249) [reply client/src/Pages/Auth/ForgotPassword.jsx:188]: @Owaiseimdad `errors.email` returns the `authRegisterEmailInvalid` and `authRegisterEmailRequired` and it should be passed in `t()` to print the translation string.

**Comment by sonvir249** [comment]
> @sonvir249 please make your changes and test it locally and add screenshots for reference.

@Owaiseimdad @Owaiseimdad thanks for the review and detailed comments. I appreciate that.
I added all the details and screenshots in #2239 when I created the issue. As per you comment I've updated the PR description.

**Comment by gorkem-bwl** [comment]
> > @sonvir249 please make your changes and test it locally and add screenshots for reference.
> 
> @Owaiseimdad @Owaiseimdad thanks for the review and detailed comments. I appreciate that. I added all the details and screenshots in #2239 when I created the issue. As per you comment I've updated the PR description.

Thanks @sonvir249. The screenshot is for the PR, not the issue, eg. reflects what you did rather than what the issue is. For this reason we are asking it to be added to the PR instead.

**Review by Br0wnHammer — APPROVED** [review]
LGTM! Thanks for the quick revisions and for explaining your approach to us. We appreciate your contributions.

**Comment by Br0wnHammer** [comment]
@ajhollid this is fine for merging.

**Comment by ajhollid** [comment]
Hey @sonvir249 , just a heads up we want to remove package-lock.json from the RP, not delete it from the project.

If you're not especially familiar with the process of ammending your git history it may be faster/easier to just open a new PR.  Thanks!

**Comment by sonvir249** [comment]
> Hey @sonvir249 , just a heads up we want to remove package-lock.json from the RP, not delete it from the project.
> 
> If you're not especially familiar with the process of ammending your git history it may be faster/easier to just open a new PR. Thanks!

@ajhollid I've updated current PR with develop branch. Please let me know if any other changes are needed. Thanks!
